travis:
  secure:
    BINSTAR_TOKEN: pSOCQhoVW/tWqYuX826lsW3vGnKbSBzJlj5gy3Cyd88v1yaDwbU98a8aFYdQdecdzMqzze2gySutySfQ0hnLhARwJ580F8zvOXPMfUlK6ke0IFmbTtWx+Q4JJz8WrEgxMC2pDv7UZXBbCCggpjri2ruXj/4fPt4IkzGrzYdljrrpmB+7NoHObBn3enyi+G3Ab7w3VKP9coewS8/zz4wzlG44OOonN+Ru8AzQWgx2giJDfDKMDrq6JDoi55r4XZ13aGL6ZdzTF2b5DoWM/Gf8WXEDT8nJxmgIOxWhgc6BGNxoD3HMIsO3J85QLAhV0DuQxXimdGj713FUIVFVrsJPSUAqBrRvBVdgJYaoUHzeyWpSG4oO1eM6eDtQ/K2hkh0fOcZvuifP6TBun/A1shP2m57SzXfe2jahdMS4JiiAWQB8z+tnNfhX7gGw5dBfkkxRvPqTLYlcWaSyZ/3Yqe+vRt4Q7cjHxg5TQi01ECTx/qi9pRe95/KNFZfpabA71NzOY3Klga3apN8IMSz1j+Rf1QsGrhOmTo/UgI4+w1F2UMnWo/4gobCpTXaCM+wLG8zZ5T4zFCo9D9U/F1po4BlqMUiFhKEEcWeqo6iNu9XN02N122ik8iJ5HAMb5v7gHzhoqBuNLDETZ2p1jpY+PXieIPaRJendZj/Pt9Bx81rp4zQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
